"@generated by @aspect_rules_js//npm/private:npm_translate_lock.bzl from pnpm lock file @//:pnpm-lock.yaml"

# buildifier: disable=bzl-visibility
load("@aspect_rules_js//npm/private:npm_linked_packages.bzl", "npm_linked_packages")
load("@npm__rollup__2.70.2__links//:defs.bzl", link_0_direct = "npm_link_imported_package_direct", link_0_store = "npm_link_imported_package_store")

def npm_link_all_packages(name = "node_modules", imported_links = []):
    """Generated list of npm_link_package() target generators and first-party linked packages corresponding to the packages in @//:pnpm-lock.yaml

    Args:
        name: name of catch all target to generate for all packages linked
        imported_links: optional list link functions from manually imported packages
            that were fetched with npm_import rules,

            For example,

            ```
            load("@npm//:defs.bzl", "npm_link_all_packages")
            load("@npm_meaning-of-life__links//:defs.bzl", npm_link_meaning_of_life = "npm_link_imported_package")

            npm_link_all_packages(
                name = "node_modules",
                imported_links = [
                    npm_link_meaning_of_life,
                ],
            )```
    """

    root_package = ""
    direct_packages = [""]
    is_root = native.package_name() == root_package
    is_direct = native.package_name() in direct_packages
    if not is_root and not is_direct:
        msg = "The npm_link_all_packages() macro loaded from @npm//:defs.bzl and called in bazel package '%s' may only be called in the bazel package(s) corresponding to the root package '' and packages ['']" % native.package_name()
        fail(msg)
    direct_targets = []
    scoped_direct_targets = {}

    for link_fn in imported_links:
        new_direct_targets, new_scoped_targets = link_fn(name)
        direct_targets.extend(new_direct_targets)
        for _scope, _targets in new_scoped_targets.items():
            scoped_direct_targets[_scope] = scoped_direct_targets[_scope] + _targets if _scope in scoped_direct_targets else _targets

    if is_root:
        link_0_store(name = "{}/rollup".format(name))
    if is_direct:
        if native.package_name() == "":
            direct_targets.append(link_0_direct(name = "{}/rollup".format(name)))

    for scope, scoped_targets in scoped_direct_targets.items():
        npm_linked_packages(
            name = "{}/{}".format(name, scope),
            srcs = scoped_targets,
            tags = ["manual"],
            visibility = ["//visibility:public"],
        )

    npm_linked_packages(
        name = name,
        srcs = direct_targets,
        tags = ["manual"],
        visibility = ["//visibility:public"],
    )
