"@generated by translate_pnpm_lock.bzl from //:pnpm-lock.yaml"

load("@aspect_rules_js//js:npm_import.bzl", "npm_import")

# buildifier: disable=function-docstring
def npm_repositories():
    npm_import(
        name = "npm__fsevents_2.3.2",
        integrity = "sha512-xiqMQR4xAeHTuB9uWm+fFRcIOgKBMiOBP+eXiyT7jsgVCq1bkVygt00oASowB7EdtpOHaaPgKt812P9ab+DDKA==",
        link_package_guard = "",
        package = "fsevents",
        version = "2.3.2",
        transitive_closure = {
            "fsevents": ["2.3.2"],
        },
        indirect = True,
    )

    npm_import(
        name = "npm__rollup_2.70.2",
        integrity = "sha512-EitogNZnfku65I1DD5Mxe8JYRUCy0hkK5X84IlDtUs+O6JRMpRciXTzyCUuX11b5L5pvjH+OmFXiQ3XjabcXgg==",
        link_package_guard = "",
        package = "rollup",
        version = "2.70.2",
        transitive_closure = {
            "rollup": ["2.70.2"],
        },
    )
