workspace(name = "e2e")

local_repository(
    name = "aspect_rules_rollup",
    path = "..",
)

# Fetch dependencies which users need as well
load("@aspect_rules_rollup//rollup:repositories.bzl", "rules_rollup_dependencies")

rules_rollup_dependencies()

load("@aspect_rules_rollup//rollup:configure.bzl", "rollup_register_toolchains")

rollup_register_toolchains()

# Set-up rules_js
load("@aspect_rules_js//js:repositories.bzl", "js_dependencies")

js_dependencies()

load("@aspect_rules_js//js:configure.bzl", "js_configure")

js_configure()

load("@aspect_rules_js//js:npm_import.bzl", "translate_pnpm_lock")

translate_pnpm_lock(
    name = "npm",
    enable_lifecycle_hooks = False,
    pnpm_lock = "//:pnpm-lock.yaml",
)

load("@npm//:repositories.bzl", "npm_repositories")

npm_repositories()