name: CI

# Controls when the action will run
on:
    # Triggers the workflow on push or pull request events but only for the main branch
    push:
        branches: [main]
    pull_request:
        branches: [main]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

concurrency:
    # Cancel previous actions from the same PR or branch except 'main' branch.
    # See https://docs.github.com/en/actions/using-jobs/using-concurrency and https://docs.github.com/en/actions/learn-github-actions/contexts for more info.
    group: concurrency-group::${{ github.workflow }}::${{ github.event.pull_request.number > 0 && format('pr-{0}', github.event.pull_request.number) || github.ref_name }}${{ github.ref_name == 'main' && format('::{0}', github.run_id) || ''}}
    cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
    # MacOS and Windows smoke tests
    # Only run on main branch (not PRs) to minimize minutes (billed at 10X and 2X respectively)
    # https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#included-storage-and-minutes
    # Linux is tested on Aspect Workflows
    test:
        if: github.ref_name == 'main' || contains(github.head_ref, 'macos') || contains(github.head_ref, 'windows')
        runs-on: ${{ matrix.os }}-latest
        strategy:
            fail-fast: false
            matrix:
                bzlmod: [1, 0]
                os: [macos, windows]
                folder:
                    - '.'
                    - 'e2e/smoke'
                    - 'e2e/smoke_rjs3'
                exclude:
                    # These workspaces are only tested with bzlmod
                    - folder: .
                      bzlmod: 0
                    - folder: e2e/smoke_rjs3
                      bzlmod: 0
        steps:
            - uses: actions/checkout@v4

            - name: Setup Bazel
              uses: bazel-contrib/setup-bazel@0.18.0
              with:
                  bazelisk-cache: true
                  disk-cache: ${{ matrix.bzlmod }}-${{ matrix.os }}-${{ matrix.folder }}
                  repository-cache: true

            - name: Get Bazel major version
              id: bazel-version
              shell: bash
              run: echo "major=$(head -n 1 .bazelversion | cut -c1)" >> $GITHUB_OUTPUT

            # TODO: remove this block once we have Aspect CLI Windows releases
            - name: Don't use Aspect CLI on Windows
              if: matrix.os == 'windows'
              working-directory: ${{ matrix.folder }}
              shell: bash
              run: rm -f .bazeliskrc

            - name: bazel test //...
              working-directory: ${{ matrix.folder }}
              shell: bash
              run: |
                  bazel \
                    --bazelrc=${GITHUB_WORKSPACE//\\/\/}/.github/workflows/ci.bazelrc \
                    test \
                    --test_tag_filters=-skip-on-bazel${{ steps.bazel-version.outputs.major }} \
                    --build_tag_filters=-skip-on-bazel${{ steps.bazel-version.outputs.major }} \
                    --enable_bzlmod=${{ matrix.bzlmod }} \
                    //...
